jobs:
  build:
    docker:
      - image: archlinux
    resource_class: medium
    steps:
      - run:
          name: Install deps
          command: |
            pacman -Syu --noconfirm git openssh go
      - run:
          name: Check deps
          command: |
            # should be 2.10+ in order to support SSH_GIT_COMMAND env var
            # See https://stackoverflow.com/a/48878551
            git version
      - add_ssh_keys:
          fingerprints:
            - "d4:b6:1d:94:27:47:cf:a6:92:c9:0f:8e:93:53:d9:2f"
      - run: |
          mkdir -p ~/.ssh
          echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          ' >> ~/.ssh/known_hosts
          
          ssh-keyscan github.com
          
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Manually clone
          command: |         
            export GIT_SSH_COMMAND="ssh -vvvv -o StrictHostKeyChecking=no -o PubkeyAcceptedAlgorithms=rsa-sha2-256"
            /bin/git clone "${CIRCLE_REPOSITORY_URL}" trunk
