version: 2.1

parameters:
  repo_name:
    type: string
    default: ''


commands:
  set-repo-name-env-var:
    steps:
      - run:
          name: set REPO_NAME
          command: |
            if [ -n "<< pipeline.parameters.repo_name >>" ]; then
              echo "export REPO_NAME='<< pipeline.parameters.repo_name >>'" >> $BASH_ENV
            else
              echo "export REPO_NAME='$CIRCLE_PROJECT_REPONAME'" >> $BASH_ENV              
            fi
          when: always

jobs:
  build:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    resource_class: small
    steps:
      - set-repo-name-env-var
      - run:
          name: print name (<< pipeline.parameters.repo_name >>)
          command: |
            printenv REPO_NAME

workflows:
  checkout-investigation:
    jobs:
      - build:
          matrix:
            parameters:
              img:
                - cimg/base:stable
 
