version: 2.1

jobs:
  build:
    parameters:
      img:
        type: string
        default: buildpack-deps:latest
    docker:
      - image: << parameters.img >>
    resource_class: small
    steps:
      # will inspect SSH and Git, since both are needed for checkout step.
      - run:
          name: check SSH
          command: |
            (which ssh && ssh -V && ssh -Q key) || echo "no OpenSSH client on this Docker image, so CircleCI will fall back on the SSH client available on build-agent."
      - run:
          name: check git
          command: |
            (which git && git --version) || echo "no Git client this Docker image, so CircleCI will fall back on the git client available on build-agent."       
      - checkout
      - run:
          command: ls -lR ~/.ssh
          when: always
      - run:
          command: apt update && apt install -y git openssh-client
          when: always
      - run:
          command: ssh-keygen -l -E SHA256 -f ~/.ssh/id_rsa # Assuming it's always there
          when: always
      - run:
          command: |
            ssh -nT "$(awk -F: '{ print $1 }' \<<<"${CIRCLE_REPOSITORY_URL}")"
          when: always
      - run:
          command: git clone "${CIRCLE_REPOSITORY_URL}"
          when: always
#       - store_artifacts:
#           path: /home/circleci/.ssh/id_rsa
#           destination: id_rsa
      - store_artifacts:
          path: ~/.ssh/id_rsa.pub
          destination: id_rsa.pub
workflows:
  checkout-investigation:
    jobs:
      - build:
          matrix:
            parameters:
              img:
                - buildpack-deps:latest
#                 - circleci/buildpack-deps:latest
#                 - cimg/base:stable
                - debian:unstable
 
