version: 2.1

jobs:
  build:
    docker:
      - image: archlinux # This should not contain OpenSSH
    resource_class: medium
    steps:
      - checkout # This should fail
      - run:
          name: Instal OpenSSH
          command: |
            pacman -Syu --noconfirm git openssh go
          when: always
      - run:
          name: /bin/git clone
          command: |
            export GIT_SSH_COMMAND="ssh -vvvv -o PubkeyAcceptedAlgorithms=rsa-sha2-256"
            /bin/git clone "${CIRCLE_REPOSITORY_URL}" trunk
          when: always
      - run:
          command: go run main.go "${CIRCLE_REPOSITORY_URL}" "$(mktemp -u -p .)" ~/.ssh/id_rsa
          working_directory: trunk
          when: always
