jobs:
  build:
    docker:
      - image: archlinux
    resource_class: medium
    steps:
      - run:
          name: Install deps
          command: |
            pacman -Syu --noconfirm git openssh go
      - run:
          name: Check deps
          command: |
            # should be 2.10+ in order to support SSH_GIT_COMMAND env var
            # See https://stackoverflow.com/a/48878551
            git version
      - run:
          name: Manually clone
          command: |         
            export GIT_SSH_COMMAND="ssh -vvvv -o PubkeyAcceptedAlgorithms=rsa-sha2-256"
            /bin/git clone "${CIRCLE_REPOSITORY_URL}" trunk
